In [65]:
import pandas as pd 
from preprocess.handle_duplicate import drop_duplicates

In [68]:
data_path = r"D:\car-price-prediction\data\eda_vietnamese-car-prices-dataset.csv"
eda_data = pd.read_csv(data_path)

In [69]:
eda_data.head(5)

,names,prices,location,brand,model,year,status,odo,origin,style,transmission,exterior_color,interior_color,seats,doors,drive,description,fuel,volumne
0,Hyundai Tucson 2.0 AT Đặc biệt - 2026,812000000,Hà Nội,Hyundai,Tucson,2026,new,0,assemble,Crossover,auto,black,black,5,5,fwd,"Giá tốt nhất, đăng kí đăng kiểm xe hỗ trợ cho ...",gasonline,2.0
1,Hyundai Palisade Prestige 2.2 AT HTRAC - 2025,1466000000,Hà Nội,Hyundai,Palisade,2025,new,0,assemble,SUV,auto,white,red,6,5,awd,"Giá tốt nhất, đăng kí đăng kiểm xe hỗ trợ cho ...",diesel,2.2
2,Mercedes Benz GLC 300 4Matic - 2023,2278000000,Hồ Chí Minh,Mercedes Benz,GLC,2023,used,19000,assemble,SUV,auto,black,multicolor,5,5,awd,Mercedes GLC300 4Matic 2023 lướt nhẹ 19.000km ...,gasonline,2.0
3,Volkswagen Tiguan Allspace - 2023,1299000000,Hồ Chí Minh,Volkswagen,Tiguan,2023,used,9000,import,SUV,auto,blue,black,7,5,awd,Volkswagen Tiguan All Space siêu lướt 9.000km ...,gasonline,2.0
4,Mercedes Benz GLB 35 4Matic - 2022,1758000000,Hồ Chí Minh,Mercedes Benz,GLB,2022,used,26000,import,SUV,auto,red,black,7,5,awd,ĐAM MÊ TỐC ĐỘ NHƯNG VẪN PHẢI LO CHO GIA ĐÌNH? ...,gasonline,2.0

In [70]:
eda_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 24740 entries, 0 to 24739
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   names           24740 non-null  str
 1   prices          24740 non-null  int64
 2   location        24740 non-null  str
 3   brand           24740 non-null  str
 4   model           24729 non-null  str
 5   year            24740 non-null  int64
 6   status          24740 non-null  str
 7   odo             24740 non-null  int64
 8   origin          24740 non-null  str
 9   style           24740 non-null  str
 10  transmission    22387 non-null  str
 11  exterior_color  24740 non-null  str
 12  interior_color  24740 non-null  str
 13  seats           24740 non-null  int64
 14  doors           24740 non-null  int64
 15  drive           24740 non-null  str
 16  description     24740 non-null  str
 17  fuel            24727 non-null  str
 18  volumne         22906 non-null  float64
dtypes: float64(1), int64(5), str(13)
memory usage: 3.6 MB

In [79]:
eda_data = eda_data.drop('names', axis=1)
eda_data = drop_duplicates(eda_data, True)

Total duplicated rows :  2

In [80]:
eda_data.info()

<class 'pandas.DataFrame'>
Index: 17330 entries, 0 to 24739
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   prices          17330 non-null  int64
 1   location        17330 non-null  str
 2   brand           17330 non-null  str
 3   model           17320 non-null  str
 4   year            17330 non-null  int64
 5   status          17330 non-null  str
 6   odo             17330 non-null  int64
 7   origin          17330 non-null  str
 8   style           17330 non-null  str
 9   transmission    15478 non-null  str
 10  exterior_color  17330 non-null  str
 11  interior_color  17330 non-null  str
 12  seats           17330 non-null  int64
 13  doors           17330 non-null  int64
 14  drive           17330 non-null  str
 15  description     17330 non-null  str
 16  fuel            17327 non-null  str
 17  volumne         16153 non-null  float64
dtypes: float64(1), int64(5), str(12)
memory usage: 2.5 MB

In [81]:
eda_data[eda_data["fuel"].isna()]

,prices,location,brand,model,year,status,odo,origin,style,transmission,exterior_color,interior_color,seats,doors,drive,description,fuel,volumne
5807,5699000000,Hà Nội,Toyota,Land Cruiser,2026,used,7900,import,SUV,NaN,white,cream,8,0,-,Land Cruiser Lc300 model 2026 sx 2025 chuẩn 1 ...,NaN,NaN
12823,5050000000,Hà Nội,Toyota,Land Cruiser,2023,used,46000,import,SUV,NaN,black,black,7,0,-,"Toyota LC300 sản xuất 2023, độ VXR và loa LX60...",NaN,NaN
12867,5250000000,Hà Nội,Toyota,Land Cruiser,2024,used,3000,import,SUV,NaN,black,black,7,0,-,"Toyota LC300 sản xuất 2024, đi 3v km. Xe đẹp 1...",NaN,NaN

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer = SimpleImputer(strategy="most_frequent")
eda_data[["transmission"]] = imputer.fit_transform(eda_data[["transmission"]]) # Theo lý thuyết thì đa số dòng xe hiện tại sẽ sử dụng hộp số tự động nên chỉ cần fill tự động theo mode là đủ

In [ ]:
# HANDLE FUEL AND VOULUME 
eda_data["fuel"] = eda_data["fuel"].fillna(eda_data.groupby(["brand", "model"])["fuel"].transform(lambda x: x.mode().iloc[0])) # Theo lý thuyết đây là dữ liệu khuyết thiếu MCR, ta có thể suy luận rầng loại nhiên liệu chúng xài sẽ tương tự những mẫu của nó có sẵn
eda_data["volumne"] = eda_data["volumne"].fillna(eda_data.groupby(["brand", "model"])["volumne"].transform("mean")) # Theo lý thuyết đây cũng là dữ liệu khuyết thiếu MCR, nhưng ta có thể suy luận rằng dung tích xy lanh nó cũng sẽ trùng với những mẫu xe cùng dòng
eda_data["volumne"] = eda_data["volumne"].fillna(0) # Xử lý đối với loại xe điện

In [102]:
eda_data.info()

<class 'pandas.DataFrame'>
Index: 17330 entries, 0 to 24739
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   prices          17330 non-null  int64
 1   location        17330 non-null  str
 2   brand           17330 non-null  str
 3   model           17320 non-null  str
 4   year            17330 non-null  int64
 5   status          17330 non-null  str
 6   odo             17330 non-null  int64
 7   origin          17330 non-null  str
 8   style           17330 non-null  str
 9   transmission    17330 non-null  str
 10  exterior_color  17330 non-null  str
 11  interior_color  17330 non-null  str
 12  seats           17330 non-null  int64
 13  doors           17330 non-null  int64
 14  drive           17330 non-null  str
 15  description     17330 non-null  str
 16  fuel            17330 non-null  str
 17  volumne         17330 non-null  float64
dtypes: float64(1), int64(5), str(12)
memory usage: 2.5 MB


imputer.fit(train.select_dtypes('float64'))
cols_float = list(train.select_dtypes('float64').columns)
train[cols_float] = imputer.transform(train.select_dtypes('float64'))

In [7]:
# PROCESSOR INSTRUCTION 
# 1. Remove Name , Description  
# 2. Map Location Back To New Province
# 3. Because We Know That New Car wont have odo so we remove Status
# 4. Engine we split it into 2 new variables called fuel, volumn
# 5. EDA 
# 6. Encoder 
# 7. Baseline model for regression tasks.

In [ ]:
# EDA INSTRUCTION 
# -> prices (min, max, mean, median, std...)
# -> location (how many provinces, cars for sales by each province)
# -> brand (how much prices by each brand)